import React from "react";
import Avatar from "@material-ui/core/Avatar";
import Head from "next/head";
import Box from "@material-ui/core/Box";
import Grid from "@material-ui/core/Grid";
import Typography from "@material-ui/core/Typography";
import Paper from "@material-ui/core/Paper";
import List from "@material-ui/core/List";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import ListItemSecondaryAction from "@material-ui/core/ListItemSecondaryAction";
import ListItemText from "@material-ui/core/ListItemText";
import Checkbox from "@material-ui/core/Checkbox";
import IconButton from "@material-ui/core/IconButton";
import CommentIcon from "@material-ui/icons/Comment";
import { useRouter } from "next/router";

const Home = () => {
  return (
    <Box>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <title>Resume</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container>
          <Grid item md={12} sm={12} xs={12}>
            <Box mt={6} mb={3}></Box>
          </Grid>
        </Grid>
        <Grid container>
          <Grid item sm={12} md={1} xs={12}></Grid>
          <Grid
            container
            direction="row"
            justifyContent="center"
            alignItems="center"
            item
            sm={12}
            md={10}
            xs={12}
          >
            <Box style={{ maxWidth: "100%" }}>
              <Grid item sm={12} md={2} xs={12}></Grid>
              <Grid
                container
                direction="row"
                justifyContent="center"
                alignItems="center"
                item
                sm={12}
                md={8}
                xs={12}
              >
                <Avatar
                  style={{
                    width: "90px",
                    height: "90px",
                    margin: "auto",
                  }}
                  align="center"
                  alt="my pic"
                  src="https://avatars.githubusercontent.com/u/49751060?v=4"
                />
                <Box mt={3}>
                  <Typography color="primary" variant="h5">
                    GAIYA M. OBED
                  </Typography>
                  <Typography color="primary" variant="paragraph">
                    Software Developer
                  </Typography>
                </Box>
              </Grid>
              <Grid item sm={12} md={2} xs={12}></Grid>
            </Box>
          </Grid>
          <Grid item sm={12} md={1} xs={12}></Grid>
          {/* DETAILS */}
          <Grid
            container
            direction="row"
            justifyContent="space-between"
            alignItems="center"
            item
            sm={12}
            md={12}
            xl={12}
          >
            <Typography>EMAIL: gaiyaobed94@gmail.com</Typography>
            <Typography>PHONE: 07058149795</Typography>
            <Typography> GITHUB: https://github.com/gaiyadev </Typography>
          </Grid>
          {/* ADDRES */}
          <Grid
            container
            drection="row"
            justifyContent="flex-start"
            alignItems="center"
            item
            sm={12}
            md={12}
            xl={12}
          >
            <Typography> ADDRESS: Kaduna, Nigeria.</Typography>
          </Grid>
          {/* profile */}
          <Grid item sm={12} md={12} xl={12}>
            <Box mt={12}>
              <Typography variant="h6" color="primary">
                PROFILE{" "}
              </Typography>
              <Typography variant="paragraph">
                Results-oriented Web Application Developer with considerable
                training and development experience in Web development using
                Laravel and Nodejs, and in all stages of design, coding, and
                testing of Web applications.
              </Typography>
            </Box>
          </Grid>

          {/* Education */}
          <Grid item sm={12} md={12} xl={12}>
            <Box mt={4}>
              <Typography variant="h6" color="primary">
                EDUCATION BACKGROUND
              </Typography>
              <ListItem>
                <ListItemIcon>
                  Kaduna State University <br />
                  <br />
                  BSc(Hons) Mathematics
                </ListItemIcon>
                <ListItemText />
                <ListItemSecondaryAction>
                  <Typography>Feb 2012 — Feb 2017</Typography>
                </ListItemSecondaryAction>
              </ListItem>
              {/* 2 */}
              <ListItem>
                <ListItemIcon>
                  Fedearal Science and Technical College, Kafanchan University{" "}
                  <br />
                  <br />
                  S.S.C.E.
                </ListItemIcon>
                <ListItemText />
                <ListItemSecondaryAction>
                  <Typography>Feb 2005 — Feb 2016</Typography>
                </ListItemSecondaryAction>
              </ListItem>
            </Box>
          </Grid>

          {/* work history */}
          <Grid item sm={12} md={12} xl={12}>
            <Box mt={4}>
              <Typography variant="h6" color="primary">
                EMPLOYMENT HISTORY
              </Typography>
              <ListItem>
                <ListItemIcon>
                  Remote Software Engineer and Lead Instructor at Tribesquare
                  <br />
                  <br />
                  Jabi, Abuja
                </ListItemIcon>
                <ListItemText />
                <ListItemSecondaryAction>
                  <Typography>May 2021 — Jun 2021</Typography>
                </ListItemSecondaryAction>
              </ListItem>
              {/* 2 */}
              <ListItem>
                <ListItemIcon>
                  Software Developer at Izzah Platforms
                  <br />
                  <br />
                  Kaduna
                </ListItemIcon>
                <ListItemText />
                <ListItemSecondaryAction>
                  <Typography>2021 — Present</Typography>
                </ListItemSecondaryAction>
              </ListItem>
              {/* 3 */}
              <ListItem>
                <ListItemIcon>
                  Faculty at NIIT Kaduna Centre.
                  <br />
                  <br />
                  Kaduna
                </ListItemIcon>
                <ListItemText />
                <ListItemSecondaryAction>
                  <Typography>Jun 2019 — Present</Typography>
                </ListItemSecondaryAction>
              </ListItem>
              {/* 4 */}
              <ListItem>
                <ListItemIcon>
                  Remote NodeJs Developer at Lexington Technology <br />
                  <br />
                  Kaduna
                </ListItemIcon>
                <ListItemText />
                <ListItemSecondaryAction>
                  <Typography>Jun 2019 — Present</Typography>
                </ListItemSecondaryAction>
              </ListItem>
            </Box>
          </Grid>
          {/* SKILLS */}
          <Grid item sm={12} md={12} xl={12}>
            <Box mt={4}>
              <Typography variant="h6" color="primary">
                SKILLS
              </Typography>
              
              <ListItem>
                <ListItemIcon>
                  Reactjs <br />
                  <br />
                  React-Native <br /> <br />
                  NextJs
                </ListItemIcon>
                <ListItemText />
              </ListItem>
              {/* 2 */}
              <ListItem>
                <ListItemIcon>
                  VueJs <br />
                  <br />
                  NuxtJs <br /> <br />
                </ListItemIcon>
                <ListItemText />
              </ListItem>{" "}
              <ListItem>
                <ListItemIcon>
                  NodeJs <br />
                  <br />
                  ExpressJs <br /> <br />
                  AdonisJs <br /> <br />
                  Typescript <br /> <br />
                  Postgressdb <br /> <br />
                  NestJs <br /> <br />
                  MongoDb <br /> <br />
                </ListItemIcon>
                <ListItemText />
              </ListItem>{" "}
              <ListItem>
                <ListItemIcon>
                  <br />
                  Postgressdb <br /> <br />
                  MongoDb <br /> <br />
                  MYSQL <br /> <br />
                </ListItemIcon>
                <ListItemText />
              </ListItem>
              <ListItem>
                <ListItemIcon>
                  <br />
                  PHP <br /> <br />
                  Laravel <br /> <br />
                  Lumen <br /> <br />
                </ListItemIcon>
                <ListItemText />
              </ListItem>{" "}
              <ListItem>
                <ListItemIcon>
                  <br />
                  Python <br /> <br />
                  Django <br /> <br />
                </ListItemIcon>
                <ListItemText />
              </ListItem>
            </Box>
          </Grid>
        </Grid>
      </main>
    </Box>
  );
};
Home.layout = "defaultLayout";
export default Home;
